# Generated by Django 3.1 on 2020-08-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
        ),
    ]
